"""Shared infrastructure for the Python experimental analysis."""

from .cross_validation import (
    CandidateScore,
    CandidateSelectionResult,
    InnerFold,
    NestedCrossValidationPlan,
    OuterFold,
    make_nested_stratified_plan,
    outer_test_fold_by_sample,
    select_candidate,
    validate_nested_cross_validation_plan,
)
from .statistics import (
    AbsoluteBootstrapMetrics,
    BootstrapScalarSummary,
    ClassificationBootstrapResult,
    ClassificationMetricSummary,
    ClassificationMetrics,
    ConfidenceInterval,
    DifferenceBootstrapMetrics,
    FoldMetrics,
    HierarchicalPairedBootstrapComparison,
    MetricDifference,
    MetricSummary,
    OutOfFoldEvaluation,
    PairedBootstrapComparison,
    RealizationAveragedBootstrapMetrics,
    accuracy,
    classification_metrics,
    evaluate_out_of_fold_predictions,
    hierarchical_paired_stratified_bootstrap,
    macro_f1,
    metrics_by_fold,
    paired_metric_difference,
    paired_stratified_bootstrap,
    stratified_bootstrap,
    summarize_fold_metrics,
)


__all__ = (
    "InnerFold",
    "OuterFold",
    "NestedCrossValidationPlan",
    "CandidateScore",
    "CandidateSelectionResult",
    "make_nested_stratified_plan",
    "validate_nested_cross_validation_plan",
    "outer_test_fold_by_sample",
    "select_candidate",
    "ClassificationMetrics",
    "MetricDifference",
    "FoldMetrics",
    "MetricSummary",
    "ClassificationMetricSummary",
    "OutOfFoldEvaluation",
    "ConfidenceInterval",
    "BootstrapScalarSummary",
    "AbsoluteBootstrapMetrics",
    "DifferenceBootstrapMetrics",
    "RealizationAveragedBootstrapMetrics",
    "ClassificationBootstrapResult",
    "PairedBootstrapComparison",
    "HierarchicalPairedBootstrapComparison",
    "classification_metrics",
    "accuracy",
    "macro_f1",
    "metrics_by_fold",
    "summarize_fold_metrics",
    "evaluate_out_of_fold_predictions",
    "paired_metric_difference",
    "stratified_bootstrap",
    "paired_stratified_bootstrap",
    "hierarchical_paired_stratified_bootstrap",
)